spring:
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://47.105.165.183:3306/order_master?characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
        username: root
        password: root1234@#
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://47.105.165.183:3306/order_slave?characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
        username: root
        password: root1234@#
    masterslave:
      load-balance-algorithm-type: round_robin  # round_robin 读库轮询，random 随机
      name: dataSource
      master-data-source-name: master
      slave-data-source-names: slave
    props:
      sql: show